common: &default_settings
  app_name: people
  license_key: '0797ce8b6b2f8930a5f136ff0d6379dd6a53ec65'
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  apdex_t: 0.5
  capture_params: true

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: people (staging)

production:
  <<: *default_settings
  monitor_mode: true
